### ISSUE TITLE
Mutable or Buildable Operations

### ISSUE THREAD

**Issue by rydrman** [ubnt-intrepid/polyfuse#91] opened 2020-11-04 19:57 UTC
First off thanks for the awesome library!

I am looking into unit testing some specific behaviour of polyfuse `Filesystems`. So far it seems really nice to pass around the `polyfuse::op::*` structures when handling an operation, which I like. The problem that I run into is that there is no mechanism to build one of these operations in a unit test scenario - since they are all very locked down. 

I'm wondering what the thoughts are one opening up these types to be constructed or modified safely so that they can be used in testing and other more advanced mapping or middleware scenarios - thanks!

**Comment by ubnt-intrepid** [comment] 2020-11-06 10:24
@rydrman It seems a very good point of view.

The current definition of `Operation` and its variants was designed with the intention of minimizing `memcpy` on decoding, but as you pointed out, it did not consider the modification of the operation values.

My current idea is to abstarct each FUSE operation as traits instead of concrete type provided by `polyfuse` crate, and `Filesystem` has callbacks for each operation (similar to `fuse-rs`):

```rust
#[async_trait]
trait Filesystem {
    async fn lookup<T>(&mut self, op: T) -> Result<()>
    where
        T: ops::Lookup {
    {
        Ok(())
    }
    // ... omit
}

// ops.rs
trait Lookup {
    fn parent(&self) -> u64;
    fn name(&self) -> &OsStr;
}
```

**Comment by rydrman** [comment] 2020-11-11 19:11
Currently, I am breaking them apart to pass around - but I do like this idea. The only downside is that I'll be forced to provide my own alternative implementations for all of the possible operations, which feels a little repetitive considering that it might be done by all users of polyfuse. Would you consider providing alternative implementations as part of some kind of `polyfuse-test` package or by other means?

**Comment by ubnt-intrepid** [comment] 2020-11-19 11:56
> The only downside is that I'll be forced to provide my own alternative implementations for all of the possible operations, which feels a little repetitive considering that it might be done by all users of polyfuse. 

Repetition of trait implementations for each operation is certainly painful and seems desirable to avoid...
One alternative is to make the operation argument types as a user-modifiable concrete types, rather than as trait abstraction as follows:

```rust
pub struct Lookup<'a> {
    pub parent: u64,
    pub name: Cow<'a, OsStr>,
}

async fn lookup(op: Lookup<'_>, reply: ReplyEntry<'_>) -> reply::Result {
    match op.parent {
        ROOT_INO if op.name.as_bytes() == b"foo.txt" => (),
        _ => return reply.send_error(libc::ENOENT),
    }

    reply.attr(root_attr())
        .ino(ROOT_INO),
        .send()
}
```

**Comment by ubnt-intrepid** [comment] 2020-11-29 17:09
After some trial and error, I concluded that the proposed fix in this issue is not necessary because such abstraction can be added later as follows:

```rust
use polyfuse::op::Lookup;

trait MyLookup {
    fn parent(&self) -> u64;
    fn name(&self) -> &OsStr;
}

impl MyLookup for Lookup<'_> { ... }

struct MockLookupOp {}
impl My Lookup for MockLookupOp { ... }

async fn lookup<Op>(&self, op: Op)
where
    Op: MyLookup,
{ ... }
```

I close this is for now, but also very grateful for your useful ideas :)

**Closed by ubnt-intrepid** 2020-11-29 17:09 UTC
